# Generated by Django 4.2.3 on 2023-08-11 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisements', '0002_advertisements_delete_advtrtisements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='update_at',
        ),
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='auction',
            field=models.BooleanField(help_text='Отметьте, если торг уместен', verbose_name='Торг'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
